Dataset:
  # source_dataset: "videoattentiontarget"
  # source_dataset_dir: "gaze/datasets/video_dataset/"
  source_dataset: "gazefollow"
  source_dataset_dir: "gaze/datasets/gazefollow_extended/"
  num_workers: 12
  gaze_point_threshold : 0
  init_weights : "pretrained/init_weights.pt"
  # init_weights : "output/spatial_depth_late_fusion_gazefollow/diffusion_siga_8_norm_3_new_clamping/ckpt_last.pth"
  # eval_weights : "/media/mostafahaggag/Shared_Drive/thesis_work/Final_work/DiffusionGazeFollowingModel/output/spatial_depth_late_fusion_gazefollow/point_loss_norm_4_weighted_losses/ckpt_epoch_30.pth"
  # eval_weights : "/media/mostafahaggag/Shared_Drive/thesis_work/Final_work/DiffusionGazeFollowingModel/output/spatial_depth_late_fusion_gazefollow/point_loss_8_fine_tuneing/ckpt_epoch_60.pth"
  eval_weights : 
  lr: 2.5e-4
  epochs: 60
  evaluate_every: 5
  save_every: 5
  print_every: 10
  no_resume: false
  output_dir: "output"
  amp: 'O1'
  no_wandb: false
  no_save: false
  batch_size: 16
  input_size: 224
  output_size: 64
  weight_decay: 0
  ema_rate: 0.9999
  device: "cuda"
  channels_last: false
Diffusion:
  schedule_type: 'linear'
  unet_inout_channels: 1
  unet_inplanes: 8
  unet_residual: 1
  list_unet_inplanes_multipliers: 
      - 1
      - 2
      - 3
      - 4
  list_unet_attention_levels: 
      - 2
      - 4
      - 8
  unet_spatial_tf_heads: 4
  unet_spatial_tf_layers: 1 
  unet_context_vector: 1024
  watch_wandb: false
  train_time_steps: 1000
  sample_time_steps: 250
  unet_dropout: 0.0
  inout_weight: 100
  diffuion_weight: 100000
  adm: false
  adm_predict_xstart: true
  adm_predict_v: false
  adm_use_kl: false  
  adm_rescale_timesteps: false
  adm_rescale_learned_sigmas: false
  adm_learn_sigma: false
  conv_resample: true
  resblock_updown: false
experiment_parameter:
  factor_multiplier: 1
  diff_normalization: 3
  norm_std_flag: true
  random_flag: false
  random_sigma: 8
  is_subsample_test_set: false
  Debugging_maps: false
  eval_from_picture: false
  clip_denoised: false
  lr_schedular: false
  warmup_linear: false
  fix_snr : false
  offset_noise_strength: 0.1
  noise_changer: false
  ema_on: false
  lr_anneal_steps: 0
losses_parameters:
  kl_div_loss: false
  x_loss: true
  other_loss: false
  mse_loss_weight_type: "constant"
